export const hobbies_collection = [
    "Reading",
    "Traveling",
    "Cooking",
    "Photography",
    "Painting",
    "Gardening",
    "Writing",
    "Cycling",
    "Swimming",
    "Dancing",
    "Hiking",
    "Fishing",
    "Knitting",
    "Singing",
    "Drawing",
    "Baking",
    "Coding",
    "Birdwatching",
    "Woodworking",
    "Pottery",
    "Yoga",
    "Meditation",
    "Rock climbing",
    "Camping",
    "Golf",
    "Running",
    "Sculpting",
    "Origami",
    "Fishing",
    "Archery",
    "Chess",
    "Music",
    "Jogging",
    "Billiards",
    "Board games",
    "Crossfit",
    "Surfing",
    "Horseback riding",
    "Writing poetry",
    "Yoga",
    "Beekeeping",
    "Comic collecting",
    "Model building",
    "Video gaming",
    "Volunteer work",
    "Magic tricks",
    "Metalworking",
    "Bird watching",
    "Interior design",
    "Journaling",
    "Public speaking",
    "Homebrewing",
    "DIY projects",
    "Collecting coins",
    "Car restoration",
    "Barbecuing",
    "Wine tasting",
    "Candle making",
    "Makeup artistry",
    "Fashion design",
    "Sewing",
    "Tattoo artistry",
    "Creative writing"
];
  